name: Release Pipeline

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./ForscherTagDemo/
    - name: Build
      run: dotnet build --configuration release --no-restore ./ForscherTagDemo/
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
         repo_token: "${{ github.token }}"
         automatic_release_tag: ""
         prerelease: false
         title: "Release Build"
         files: |
           *.dll
           *.exe
           *.json
