name: Main Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./ForscherTagDemo/
    - name: Build
      run: dotnet build --configuration release --no-restore ./ForscherTagDemo/
    - name: Test
      run: dotnet test --configuration release --no-build --verbosity normal ./ForscherTagDemo/
