name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ForscherTagDemo.sln
    - name: Build
      run: dotnet build ForscherTagDemo.sln --no-restore
    - name: Test
      run: dotnet test ForscherTagDemo.sln --no-build --verbosity normal
